import Head from 'next/head';
import CreatePostModal from '../components/CreatePostModal';
import Feed from '../components/Feed';

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/headerIcon.png" />
      </Head>
      <main className="bg-gray-50 h-screen">
        <CreatePostModal />
        <Feed />
      </main>
    </>
  );
}
